---
title: "nada_scope_3"
author: "Shelby Walsh"
date: "10/27/2020"
output: html_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE, echo = FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(tidyr)
library(janitor)
library(kableExtra)
#library(car) # this package is apparently my computer's sworn nemesis
library(devtools)
library(broom)
library(ggpubr)
library(ggbeeswarm)
library(RColorBrewer)
library(effsize)
library(stargazer)
```


1. Read in the data
```{r}
all_data <- read_csv("2019_vendor_invoice.csv") %>% 
  clean_names()
```

2. Sort out irrevelant columns and drop NAs for item.
```{r}
all_data <- all_data %>% 
  select(purchase_order, vendor, receipt_id, item, unit, date, cost_unit, total_quantity, total_cost)

all_data <- all_data %>% 
  drop_na(item) # The are the "line items" for each order
# We lost 3836 rows
```

3.Group suppliers by spend, and select the top suppliers:
```{r}
spend_grouping <- all_data  %>% 
  group_by(vendor) %>% 
  summarise(cost = sum(total_cost)) %>% 
  arrange(-cost) %>% 
  head(29)
# #29 is top 80%
# This is not relevant to what we decided to do.
```

4. Group products and calculate total spend.
```{r}
# ** Note: When making changes, return to this link and run all code chunks below to be sure that everything is sorted correctly
all_products <- all_data  %>% 
  group_by(item) %>% 
  summarise(quantity = sum(total_quantity), 
            cost = sum(total_cost))
```

5. The next step is sorting products into CEDA-related categories

(1) Eggs
```{r}
# Eggs (Did not find any poultry in 2019 records)
eggs_category_1 <- all_products %>% 
 filter(grepl('Eggs|eggs', item))

# Subtract those words from all_products
all_products <- all_products[!grepl('Eggs|eggs', all_products$item),]

# Product Category Code
eggs_category_1 <- eggs_category_1 %>%
  add_column(prod_cat = 1)
```


(2) Cheese
```{r}
# Cheese (Appears to be named "Cheese,...")
cheese_category_2 <- all_products %>% 
 filter(grepl('cheese,|Cheese,', item))

# Subtract those words from all_products
all_products <- all_products[!grepl('cheese,|Cheese,', all_products$item),]

# Product Category Code
cheese_category_2 <- cheese_category_2 %>%
  add_column(prod_cat = 2)
```

(3) Meat (except poultry)
```{r}
# Basically just what they get from Two Rivers Speciality Meats
meats_category_3 <- all_products %>% 
 filter(grepl('Pepperoni|Bratwurst|Sausage|Chorizo|Jerky', item))

# Subtract those words from all_products
all_products <- all_products[!grepl('Pepperoni|Bratwurst|Sausage|Chorizo|Jerky', all_products$item),]

# Product Category Code
meats_category_3 <- meats_category_3  %>%
  add_column(prod_cat = 3)
```

(4) Fabrics
```{r}
# These are all made of fabric, primarily cotton
fabrics_category_4 <- all_products %>% 
 filter(grepl('Fabric|Filter|Bag |Bag,|Wrap', item))
# Note "bag" variations to exclude "baguette"

# Subtract those words from all_products
all_products <- all_products[!grepl('Fabric|Filter|Bag |Bag,|Wrap', all_products$item),]

# Product Category Code
fabrics_category_4 <- fabrics_category_4  %>%
  add_column(prod_cat = 4)

# ** NOTE - some of these are upcycled fabric!
```

(5) Flours
```{r}
# Flours and flour mixes
flours_category_5 <- all_products %>% 
 filter(grepl('Flour,|Flour |Pancake', item))
# Note "flour" variation exclude "flourgirl"

# Subtract those words from all_products
all_products <- all_products[!grepl('Fabric|Filter|Bag |Bag,|Wrap', all_products$item),]

# Product Category Code
flours_category_5 <- flours_category_5  %>%
  add_column(prod_cat = 5)
```

(6) Breads
```{r}
# Basically just what they get from Two Rivers Speciality Meats
breads_category_6 <- all_products %>% 
 filter(grepl('Bread|Hamburger|Crouton|Loaf', item))
# Hamburger retrieves "hamburger bun" without messing with anything sold by the bunch

# Subtract those words from all_products
all_products <- all_products[!grepl('Pepperoni|Bratwurst|Sausage|Chorizo', all_products$item),]

# Product Category Code
breads_category_6 <- breads_category_6   %>%
  add_column(prod_cat = 6)
```

(7) Cookie, cracker, pasta, and tortilla
```{r}
ccpt_category_7 <- all_products %>% 
 filter(grepl('Cookie|Macaron|Sinnabon|Crisp|Cracker|Tortilla', item))

# "Macaron" works for macaron and macaroni
# I put cookies in here because I 
```

